# Generated by Django 6.0.3 on 2026-04-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_perfume_recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='note_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=20)),
                ('season', models.CharField(max_length=100)),
                ('longevity', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfume_images/')),
                ('notes', models.ManyToManyField(related_name='perfumes', to='ai_perfume_recommender.note')),
            ],
        ),
    ]
